# 共通定義（ビルドや実行コマンドなど）
x-app-base: &app_base
  build:
    context: .
    dockerfile: Dockerfile
  working_dir: /app
  volumes:
    - ./:/app
    - ~/.aws:/root/.aws:ro # ホストのAWS認証を使う場合のみ
  command: python server.py # server.py は PORT を読む実装

services:
  # dev: ローカルParquet参照（PORT=8050）
  web-dev:
    <<: *app_base
    container_name: dash_plotly_dev
    env_file:
      - .env.dev
    ports:
      - "8050:8050"

  # stg: S3参照（PORT=8051）
  web-stg:
    <<: *app_base
    container_name: dash_plotly_stg
    env_file:
      - .env.stg
    ports:
      - "8051:8051"
