name: OIDC Smoke Test
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  whoami:
    runs-on: ubuntu-latest
    environment:
      name: "AWS_OIDC" # ← これを必ず付ける（環境を紐づけ）

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # ← Environment Secret を参照
          aws-region: ${{ vars.AWS_REGION }} # ← Environment Variable を参照
          audience: sts.amazonaws.com

      - run: aws sts get-caller-identity

      - name: Show config (例：デバッグ時のみ)
        run: |
          echo "ECR_REPO=${{ vars.ECR_REPO }}"
          echo "APP_RUNNER_SERVICE_ARN=${{ vars.APP_RUNNER_SERVICE_ARN }}"
          echo "S3_BUCKET=${{ vars.S3_BUCKET }}"
          echo "PARQUET_PREFIX=${{ vars.PARQUET_PREFIX }}"
