name: S3 Reconcile by manifest.json

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Preview only (no changes to S3)"
        type: boolean
        default: true
  push:
    branches: [main]
    paths:
      - "data/parquet/manifest.json"

permissions:
  id-token: write
  contents: read

jobs:
  reconcile:
    runs-on: ubuntu-latest
    environment:
      name: "AWS_OIDC"

    env:
      MANIFEST_PATH: data/parquet/manifest.json

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Show inputs/vars
        run: |
          echo "dry_run=${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || 'false' }}"
          echo "S3_BUCKET=${{ vars.S3_BUCKET }}"
          echo "PARQUET_PREFIX=${{ vars.PARQUET_PREFIX }}"

      - name: Validate manifest.json
        run: |
          set -euo pipefail
          test -f "$MANIFEST_PATH" || { echo "::error::manifest not found: $MANIFEST_PATH"; exit 1; }
          jq type "$MANIFEST_PATH" >/dev/null
          jq -e '.items and (.items | type=="array") and ([.items[].key] | length>0)' "$MANIFEST_PATH" >/dev/null

      - name: Upload manifest.json itself
        env:
          BUCKET: ${{ vars.S3_BUCKET }}
          PREFIX: ${{ vars.PARQUET_PREFIX }}
        run: |
          set -euo pipefail
          DEST="s3://${BUCKET}/${PREFIX%/}/manifest.json"
          echo ">> PUT $MANIFEST_PATH -> $DEST"
          aws s3 cp "$MANIFEST_PATH" "$DEST" --only-show-errors

      - name: Report missing objects listed in manifest (informational)
        env:
          BUCKET: ${{ vars.S3_BUCKET }}
          PREFIX: ${{ vars.PARQUET_PREFIX }}
        run: |
          set -euo pipefail
          mapfile -t HAVE < <(aws s3api list-objects-v2 \
            --bucket "$BUCKET" --prefix "$PREFIX" \
            --query 'Contents[].Key' --output text 2>/dev/null | tr '\t' '\n' | sed '/^$/d')
          mapfile -t WANTED_S3KEYS < <(jq -r --arg p "${PREFIX%/}/" '.items[].key | "\($p)\(.)"' "$MANIFEST_PATH")
          missing=()
          for w in "${WANTED_S3KEYS[@]}"; do
            found=false
            for h in "${HAVE[@]}"; do
              if [ "$w" = "$h" ]; then found=true; break; fi
            done
            $found || missing+=("$w")
          done
          if [ ${#missing[@]} -gt 0 ]; then
            echo "::warning::Missing objects on S3 (listed in manifest but not found):"
            printf '  - %s\n' "${missing[@]}"
          else
            echo "All manifest-listed objects exist on S3."
          fi

      - name: Delete objects NOT in manifest (make S3 clean)
        env:
          BUCKET: ${{ vars.S3_BUCKET }}
          PREFIX: ${{ vars.PARQUET_PREFIX }}
          DRYRUN: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || 'false' }}
        run: |
          set -euo pipefail
          mapfile -t HAVE < <(aws s3api list-objects-v2 \
            --bucket "$BUCKET" --prefix "$PREFIX" \
            --query 'Contents[].Key' --output text 2>/dev/null | tr '\t' '\n' | sed '/^$/d')
          echo "S3 has (${#HAVE[@]}):"
          printf '  - %s\n' "${HAVE[@]}"
          mapfile -t WANTED_S3KEYS < <(jq -r --arg p "${PREFIX%/}/" '.items[].key | "\($p)\(.)"' "$MANIFEST_PATH")
          PROTECT=("${PREFIX%/}/manifest.json")
          to_delete=()
          for key in "${HAVE[@]}"; do
            skip=false
            for w in "${WANTED_S3KEYS[@]}"; do [ "$key" = "$w" ] && { skip=true; break; }; done
            for p in "${PROTECT[@]}";    do [ "$key" = "$p" ] && { skip=true; break; }; done
            $skip || to_delete+=("$key")
          done
          echo "Extra keys to delete (${#to_delete[@]}):"
          printf '  - %s\n' "${to_delete[@]}" || true
          for key in "${to_delete[@]}"; do
            if [ "$DRYRUN" = "true" ]; then
              echo "[dry-run] would delete s3://${BUCKET}/${key}"
            else
              echo "DELETE s3://${BUCKET}/${key}"
              aws s3 rm "s3://${BUCKET}/${key}" --only-show-errors || true
            fi
          done

      - name: List objects (after reconcile)
        run: |
          aws s3 ls "s3://${{ vars.S3_BUCKET }}/${{ vars.PARQUET_PREFIX }}" --recursive
